# Generated by Django 5.2 on 2025-05-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('speciality', models.CharField(choices=[('sc', 'علوم تجريبية'), ('math', 'رياضيات'), ('lit', 'آداب')], max_length=10)),
                ('payment_receipt', models.FileField(upload_to='receipts/')),
            ],
        ),
    ]
