# Generated by Django 5.2 on 2025-05-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacregistration',
            name='username',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
