# Generated by Django 5.2 on 2025-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0002_bacregistration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10),
        ),
    ]
