# Generated by Django 5.2 on 2025-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0003_bacregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacregistration',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bacregistration',
            name='speciality',
            field=models.CharField(choices=[('sc', 'علوم تجريبية'), ('math', 'رياضيات'), ('mt', 'تقني رياضي'), ('lit', 'آداب')], max_length=10),
        ),
    ]
