# Generated by Django 5.2 on 2025-05-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0004_bacregistration_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
